services:
  api:
    build:
      context: .
      # relative to the context, so it will look for the Dockerfile in ./services/admin/Dockerfile
      dockerfile: ./Dockerfile
      args:
        - DEV=true
    # user: "1000:1000"
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PASS}
      DB_NAME: ${PG_DB}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DEBUG: ${DEBUG}
    volumes:
      - .:/code
      # - media-data:/code/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --worker-tmp-dir /tmp"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17.9
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready ${PG_USER} -d ${PG_DB}"]
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  pg-data:
  # media-data:
